/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRouter } from './IRouter.js';
export type { ZablonFlashBot } from './ZablonFlashBot.js';
export * as factories from './factories/index.js';
export { IRouter__factory } from './factories/IRouter__factory.js';
export { ZablonFlashBot__factory } from './factories/ZablonFlashBot__factory.js';