/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ZablonFlashBot {
      
    export type ArbParamsStruct = {router1: AddressLike, router2: AddressLike, path1: AddressLike[], path2: AddressLike[], amountOutMin1: BigNumberish, amountOutMin2: BigNumberish}

    export type ArbParamsStructOutput = [router1: string, router2: string, path1: string[], path2: string[], amountOutMin1: bigint, amountOutMin2: bigint] & {router1: string, router2: string, path1: string[], path2: string[], amountOutMin1: bigint, amountOutMin2: bigint }
  
    }

  export interface ZablonFlashBotInterface extends Interface {
    getFunction(nameOrSignature: "ADDRESSES_PROVIDER" | "POOL" | "executeOperation" | "owner" | "requestFlashLoan" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'ADDRESSES_PROVIDER', values?: undefined): string;
encodeFunctionData(functionFragment: 'POOL', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeOperation', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestFlashLoan', values: [AddressLike, BigNumberish, ZablonFlashBot.ArbParamsStruct]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ADDRESSES_PROVIDER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'POOL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeOperation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestFlashLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface ZablonFlashBot extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZablonFlashBot;
    waitForDeployment(): Promise<this>;

    interface: ZablonFlashBotInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADDRESSES_PROVIDER: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    POOL: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeOperation: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, premium: BigNumberish, arg3: AddressLike, params: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    requestFlashLoan: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, params: ZablonFlashBot.ArbParamsStruct, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADDRESSES_PROVIDER'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'POOL'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeOperation'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, premium: BigNumberish, arg3: AddressLike, params: BytesLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requestFlashLoan'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, params: ZablonFlashBot.ArbParamsStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }